version: '3.7'
services:
  frontend:
    hostname: frontend
    container_name: frontend
    build: ./client/
    ports:
      - '80:3000'
    volumes:
      - './client:/app'
  backend:
    hostname: backend
    container_name: backend
    build: ./server/
    ports:
      - '5001:5000'
    volumes:
      - './server:/app'
  db:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root